"""create_misconception_tables

Revision ID: 057653aef2fa
Revises: 97ab331c00af
Create Date: 2026-09-11 16:20:52.432671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '057653aef2fa'
down_revision: Union[str, Sequence[str], None] = '97ab331c00af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    misconception_tags_table = op.create_table('misconception_tags',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('name', sa.Text(), nullable=False),
        sa.Column('display_label', sa.Text(), nullable=False),
        sa.Column('concept_id', sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_misconception_tags_concept_id'), 'misconception_tags', ['concept_id'], unique=False)
    op.create_index(op.f('ix_misconception_tags_name'), 'misconception_tags', ['name'], unique=True)

    op.create_table('misconception_events',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('experiment_id', sa.UUID(), nullable=True),
        sa.Column('tag_id', sa.UUID(), nullable=False),
        sa.Column('source', sa.Text(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.CheckConstraint("source IN ('rule_based', 'ai_classified')", name="check_misconception_source"),
        sa.ForeignKeyConstraint(['tag_id'], ['misconception_tags.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_misconception_events_created_at'), 'misconception_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_misconception_events_tag_id'), 'misconception_events', ['tag_id'], unique=False)
    op.create_index(op.f('ix_misconception_events_user_id'), 'misconception_events', ['user_id'], unique=False)

    # Seed fixed taxonomy of misconception tags tied to 'entanglement'
    import uuid
    conn = op.get_bind()
    res = conn.execute(sa.text("SELECT id FROM concepts WHERE name = 'entanglement'")).fetchone()
    if res:
        entanglement_id = res[0]
        op.bulk_insert(
            misconception_tags_table,
            [
                {
                    "id": uuid.uuid4(),
                    "name": "confuses_superposition_with_classical_probability",
                    "display_label": "Confuses superposition with classical probability",
                    "concept_id": entanglement_id,
                },
                {
                    "id": uuid.uuid4(),
                    "name": "expects_correlation_without_entangling_gate",
                    "display_label": "Expects correlation without entangling gate",
                    "concept_id": entanglement_id,
                },
                {
                    "id": uuid.uuid4(),
                    "name": "misreads_zero_amplitude_as_impossible_outcome",
                    "display_label": "Misreads zero amplitude as impossible outcome",
                    "concept_id": entanglement_id,
                },
            ]
        )
    # ### end Alembic commands ###



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_misconception_events_user_id'), table_name='misconception_events')
    op.drop_index(op.f('ix_misconception_events_tag_id'), table_name='misconception_events')
    op.drop_index(op.f('ix_misconception_events_created_at'), table_name='misconception_events')
    op.drop_table('misconception_events')
    op.drop_index(op.f('ix_misconception_tags_name'), table_name='misconception_tags')
    op.drop_index(op.f('ix_misconception_tags_concept_id'), table_name='misconception_tags')
    op.drop_table('misconception_tags')
    # ### end Alembic commands ###
