"""create_concepts_and_concept_mastery

Revision ID: 97ab331c00af
Revises: 84a43014ac7d
Create Date: 2026-09-11 15:51:09.920921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97ab331c00af'
down_revision: Union[str, Sequence[str], None] = '84a43014ac7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    concepts_table = op.create_table('concepts',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('name', sa.Text(), nullable=False),
        sa.Column('description', sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_concepts_name'), 'concepts', ['name'], unique=True)
    
    op.create_table('concept_mastery',
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('concept_id', sa.UUID(), nullable=False),
        sa.Column('mastery_score', sa.Float(), nullable=False, server_default=sa.text('0.0')),
        sa.Column('attempts', sa.Integer(), nullable=False, server_default=sa.text('0')),
        sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.CheckConstraint('mastery_score >= 0.0 AND mastery_score <= 1.0', name='check_mastery_score_range'),
        sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('user_id', 'concept_id')
    )

    # Seed initial domain concepts (entanglement active, others placeholder)
    import uuid
    op.bulk_insert(
        concepts_table,
        [
            {
                "id": uuid.uuid4(),
                "name": "entanglement",
                "description": "Multi-qubit non-local correlations, Bell states, and Einstein-Podolsky-Rosen paradox.",
            },
            {
                "id": uuid.uuid4(),
                "name": "superposition",
                "description": "Single-qubit quantum states, Hadamard basis transformations, and phase coherence.",
            },
            {
                "id": uuid.uuid4(),
                "name": "gates",
                "description": "Unitary single and multi-qubit quantum logic gates (Pauli-X, Y, Z, Phase, CNOT).",
            },
            {
                "id": uuid.uuid4(),
                "name": "measurement",
                "description": "Computational basis projection, probabilistic state collapse, and statistical distributions.",
            },
        ]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('concept_mastery')
    op.drop_index(op.f('ix_concepts_name'), table_name='concepts')
    op.drop_table('concepts')
    # ### end Alembic commands ###

